test:
  adapter: postgresql
  encoding: unicode
  database: test_database
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: production_database
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: development_database
  pool: 5
